- name: Ping all and see proccess variable
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install curl
      ansible.builtin.apt:
        name: curl
        state: present
        update_cache: true
      register: apt_result
    - name: Fetch public IP
      ansible.builtin.command: curl icanhazip.com
      register: ip_result
      changed_when: false
    - name: Display IP and apt results
      ansible.builtin.debug:
        msg: "Public IP for {{ inventory_hostname }} is {{ ip_result.stdout }}. Apt result: {{ apt_result }}"
